#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Tue Mar 17 20:26:34 GMT 2026
alwaysLogTamperWarnings=true
