#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Mar 19 20:59:44 GMT 2026
colorSpace=ADOBE_RGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.7.1.zip
enableShaders=true
